### ISSUE TITLE
Colors do not display properly based on repo language.

### ISSUE THREAD

**Issue by Nsttt** [Nsttt/githunter#7]
- In repo.js Line 86.

Colors make the page crash due to being undefined.
**TypeError: Cannot read property 'color' of undefined**

**Comment by gbudjeakp** [comment]
Hey so I'm not sure if I have the perfect fix but I just tried something and I get the repo languages to show the right colors. Hope you do not mind if I make a PR for it.

**Comment by gbudjeakp** [comment]
So I've worked a fix for this bug and I'll make a pull now
